from typing import Dict, Any, List

"""
Master Registry for All 24 Indian State Land Record & Record of Rights (RoR) Portals
plus Central DILRMP (Bhu-Aadhaar) and e-Courts Services.
"""

ALL_PORTALS_REGISTRY: List[Dict[str, Any]] = [
    {
        "id": "jharkhand-jharbhoomi",
        "state": "Jharkhand",
        "portal_name": "Jharbhoomi (झारभूमि)",
        "english_title": "Jharkhand Land Records & RoR Portal",
        "hindi_title": "झारभूमि भू-अभिलेख एवं दाखिल-खारिज पोर्टल",
        "zone": "East",
        "official_url": "https://jharbhoomi.jharkhand.gov.in",
        "cadastral_gis_url": "https://jharbhunaksha.jharkhand.gov.in",
        "mutation_url": "https://jharbhoomi.jharkhand.gov.in/Operater/UserLogin",
        "tax_url": "https://jharbhulagan.jharkhand.gov.in",
        "court_url": "https://jharbhoomi.jharkhand.gov.in/MISROR/DistrictMap",
        "term_anchal": "Anchal / Circle",
        "term_record": "Khatian & Register-II",
        "term_plot": "Khesra / Plot No",
        "term_holding": "Khata Number",
        "category": "State RoR Portal",
        "description": "Comprehensive digitized land records of Jharkhand including Khatian RoR, Jamabandi Register-II, Dakhil-Kharij (Mutation), Online Lagan tax payment, Parishodhan rectification, and JharBhuNaksha cadastral maps.",
        "services": [
            {"name": "Apna Khata (Khatian RoR)", "code": "ROR", "desc": "View tenant shares, father's name, caste, and Sabik/Hal Khatian entries."},
            {"name": "Register-II (Jamabandi Ledger)", "code": "REG2", "desc": "Inspect current owner roll, tenant ledger, and annual rent demands."},
            {"name": "Online Dakhil-Kharij (Mutation)", "code": "MUTATION", "desc": "File and track statutory land mutation applications with SLA monitoring."},
            {"name": "JharBhuNaksha (GIS Cadastral)", "code": "GIS", "desc": "Interactive geo-referenced village cadastral boundary maps."},
            {"name": "Online Lagan (Land Tax)", "code": "TAX", "desc": "Pay annual land revenue lagan and download verified receipts."},
            {"name": "Parishodhan (Record Correction)", "code": "CORRECTION", "desc": "Lodge correction requests for digitised Jamabandi discrepancies."}
        ]
    },
    {
        "id": "uttar-pradesh-upbhulekh",
        "state": "Uttar Pradesh",
        "portal_name": "UP Bhulekh (यूपी भूलेख)",
        "english_title": "UP Land Records & Real-time Khatauni Portal",
        "hindi_title": "उत्तर प्रदेश राजस्व परिषद भूलेख एवं रियल टाइम खतौनी",
        "zone": "North",
        "official_url": "http://upbhulekh.gov.in",
        "cadastral_gis_url": "http://upbhunaksha.gov.in",
        "mutation_url": "http://vaad.up.nic.in",
        "tax_url": "http://bor.up.nic.in",
        "court_url": "http://vaad.up.nic.in",
        "term_anchal": "Tehsil",
        "term_record": "Khatauni RoR (खतौनी)",
        "term_plot": "Gata / Khasra No (गाटा / खसरा)",
        "term_holding": "Khata Number (खाता संख्या)",
        "category": "State RoR Portal",
        "description": "Real-time Khatauni, Gata code uniquely indexed parcels, Bhunaksha UP spatial overlays, e-Revenue Court (vaad.up.nic.in) case status, and non-agricultural (Section 80) land verification.",
        "services": [
            {"name": "Real-time Khatauni RoR", "code": "ROR", "desc": "View live updated Khatauni with unencumbered status and co-sharer details."},
            {"name": "Gata Unique Code Lookup", "code": "GATA", "desc": "16-digit unique land parcel identification code across UP villages."},
            {"name": "UP Bhu-Naksha GIS", "code": "GIS", "desc": "Vector cadastral plot maps with geo-coordinates and adjacent plot verification."},
            {"name": "e-Court (vaad.up.nic.in)", "code": "COURT", "desc": "Track revenue litigation before Tehsildar, SDM, and Board of Revenue courts."},
            {"name": "Section 80 Declaration Status", "code": "143_80", "desc": "Verify agricultural to commercial/residential conversion approvals."}
        ]
    },
    {
        "id": "bihar-biharbhumi",
        "state": "Bihar",
        "portal_name": "Bihar Bhumi (बिहार भूमि)",
        "english_title": "Bihar Land Records, Dakhil-Kharij & LPC Portal",
        "hindi_title": "बिहार सरकार राजस्व एवं भूमि सुधार विभाग",
        "zone": "East",
        "official_url": "http://biharbhumi.bihar.gov.in/Biharbhumi",
        "cadastral_gis_url": "http://bhunaksha.bihar.gov.in",
        "mutation_url": "http://biharbhumi.bihar.gov.in/Biharbhumi/MutationStatus.aspx",
        "tax_url": "http://biharbhumi.bihar.gov.in/Biharbhumi/OnlineLagan.aspx",
        "court_url": "http://dclr.bihar.gov.in",
        "term_anchal": "Anchal / Block",
        "term_record": "Jamabandi Panji & Khatian",
        "term_plot": "Khesra No (खेसरा)",
        "term_holding": "Khata No (खाता)",
        "category": "State RoR Portal",
        "description": "Bihar Bhumi portal provides digitized Jamabandi Panji, Dakhil-Kharij online status, Land Possession Certificate (LPC) issuance, Online Lagan, and DCLR revenue court dispute records.",
        "services": [
            {"name": "Apna Khata (अपना खाता देखें)", "code": "ROR", "desc": "Search Khatiyan and rights of tenant by District, Anchal, and Mauza."},
            {"name": "Jamabandi Panji (जमाबंदी पंजी)", "code": "REG2", "desc": "Inspect tenant ledger volume and page entries with plot area details."},
            {"name": "Online Dakhil Kharij Filing", "code": "MUTATION", "desc": "Apply online for land mutation and download rejection/approval orders."},
            {"name": "LPC (Land Possession Certificate)", "code": "LPC", "desc": "Apply and download statutory Land Possession Certificates."},
            {"name": "Bihar BhuNaksha GIS", "code": "GIS", "desc": "Interactive survey maps with digitized parcel boundaries."}
        ]
    },
    {
        "id": "maharashtra-mahabhumi",
        "state": "Maharashtra",
        "portal_name": "Bhulekh Mahabhumi (महाभूमि / 7/12)",
        "english_title": "Maharashtra Land Records & Mahabhulekh Portal",
        "hindi_title": "महाराष्ट्र भूमी अभिलेख (७/१२, ८अ, फेरफार)",
        "zone": "West",
        "official_url": "https://bhulekh.mahabhumi.gov.in",
        "cadastral_gis_url": "https://mahabhunaksha.mahabhumi.gov.in",
        "mutation_url": "https://digitalsatbara.mahabhumi.gov.in",
        "tax_url": "https://gras.mahakosh.gov.in",
        "court_url": "https://mcls.mahabhumi.gov.in",
        "term_anchal": "Taluka",
        "term_record": "7/12 (Satbara) & 8A Extract",
        "term_plot": "Gat / Survey Number (गट / सर्व्हे क्र.)",
        "term_holding": "Khate Number (खाते क्र.)",
        "category": "State RoR Portal",
        "description": "Maharashtra's official Mahabhulekh portal for digitally signed 7/12 (Saat Bara) extracts, 8A land holding ledgers, Ferfar (mutation entry) tracking, and Mahabhunaksha GIS cadastral overlays.",
        "services": [
            {"name": "7/12 Extract (सातबारा उतारा)", "code": "ROR", "desc": "Village Form VII & XII showing ownership, crops, and encumbrances."},
            {"name": "8A Extract (८अ खाते उतारा)", "code": "8A", "desc": "Total land assessment and area held by a single landowner."},
            {"name": "Ferfar Status (फेरफार नोंदणी)", "code": "MUTATION", "desc": "Track mutation register entries and notice objections."},
            {"name": "Mahabhunaksha GIS", "code": "GIS", "desc": "Survey number boundary maps with field measurement sketches."},
            {"name": "e-Hakk (e-हक्क प्रणाली)", "code": "E_HAKK", "desc": "Online application for rights creation, heir addition, and bank loans."}
        ]
    },
    {
        "id": "karnataka-bhoomi",
        "state": "Karnataka",
        "portal_name": "Bhoomi (ಭೂಮಿ)",
        "english_title": "Karnataka State Land Records & Bhoomi Portal",
        "hindi_title": "कर्नाटक भूमि आरटीसी (RTC Pahani) अभिलेख पोर्टल",
        "zone": "South",
        "official_url": "https://landrecords.karnataka.gov.in",
        "cadastral_gis_url": "https://landrecords.karnataka.gov.in/service3",
        "mutation_url": "https://landrecords.karnataka.gov.in/service2",
        "tax_url": "https://k2.karnataka.gov.in",
        "court_url": "https://landrecords.karnataka.gov.in/service51",
        "term_anchal": "Taluk / Hobli",
        "term_record": "RTC Pahani (ಪಹಣಿ)",
        "term_plot": "Survey / Hissa No",
        "term_holding": "Khata Number",
        "category": "State RoR Portal",
        "description": "Karnataka's pioneering Bhoomi portal providing RTC (Record of Rights, Tenancy and Crops) Pahani, Mutation Register extracts (MR), Parihara crop compensation, and cadastral revenue maps.",
        "services": [
            {"name": "View RTC Pahani (ಪಹಣಿ ವಿವರ)", "code": "ROR", "desc": "Current and historical RTC extracts with soil type, ownership, and cultivation."},
            {"name": "Mutation Register (MR Status)", "code": "MUTATION", "desc": "Real-time mutation process tracking and order generation."},
            {"name": "Revenue Map (ದಿಶಾಂಕ / ಕಂದಾಯ ನಕ್ಷೆ)", "code": "GIS", "desc": "Village maps and cadastral survey boundaries."},
            {"name": "Mojini (ಜಮೀನು ಸರ್ವೆ / ಮೋಜಿನಿ)", "code": "SURVEY", "desc": "Pre-mutation sketch (11E) and Tatkal Podi survey requests."},
            {"name": "Parihara Dispute Checker", "code": "COURT", "desc": "Verify court stays and government land classification."}
        ]
    },
    {
        "id": "andhra-pradesh-meebhoomi",
        "state": "Andhra Pradesh",
        "portal_name": "Meebhoomi (మీభూమి)",
        "english_title": "Andhra Pradesh Land Records & Meebhoomi Portal",
        "hindi_title": "आंध्र प्रदेश मीभूमि अडंगल एवं 1-B अधिकार अभिलेख",
        "zone": "South",
        "official_url": "https://meebhoomi.ap.gov.in",
        "cadastral_gis_url": "https://meebhoomi.ap.gov.in/FMB.aspx",
        "mutation_url": "https://meebhoomi.ap.gov.in",
        "tax_url": "https://cfms.ap.gov.in",
        "court_url": "https://meebhoomi.ap.gov.in/CourtCaseDetails.aspx",
        "term_anchal": "Mandal",
        "term_record": "Adangal & 1-B RoR",
        "term_plot": "Survey / Sub-Division No",
        "term_holding": "Khata / Pattadar Passbook No",
        "category": "State RoR Portal",
        "description": "Meebhoomi provides digital Adangal (Pahani), 1-B Record of Rights, Field Measurement Book (FMB) sketches, Electronic Pattadar Passbooks (e-PPB), and land dispute status.",
        "services": [
            {"name": "Your Adangal / Pahani", "code": "ROR", "desc": "Village-wise and individual crop & land possession status."},
            {"name": "1-B Record of Rights", "code": "1B", "desc": "Total land holding summary of pattadar with extent in acres."},
            {"name": "FMB (Field Measurement Book)", "code": "GIS", "desc": "Exact geometric boundaries and survey measurement sketches."},
            {"name": "Village Map (గ్రామ పటం)", "code": "MAP", "desc": "Comprehensive geo-referenced revenue village maps."},
            {"name": "Land Dispute Status", "code": "COURT", "desc": "Check revenue court case proceedings and civil injunctions."}
        ]
    },
    {
        "id": "telangana-dharani",
        "state": "Telangana",
        "portal_name": "Bhu Bharati / Dharani (ధరణಿ)",
        "english_title": "Telangana Integrated Land Records Management Portal",
        "hindi_title": "तेलंगाना धरणी एकीकृत भूमि रिकॉर्ड पोर्टल",
        "zone": "South",
        "official_url": "https://dharani.telangana.gov.in",
        "cadastral_gis_url": "https://bhubharati.telangana.gov.in",
        "mutation_url": "https://dharani.telangana.gov.in",
        "tax_url": "https://treasury.telangana.gov.in",
        "court_url": "https://dharani.telangana.gov.in/courtCasesDetails",
        "term_anchal": "Mandal",
        "term_record": "Dharani RoR-1B & Passbook",
        "term_plot": "Survey / Sub-division No",
        "term_holding": "Khata No / PPB",
        "category": "State RoR Portal",
        "description": "Dharani and Bhu Bharati integrate agricultural and non-agricultural property registration, instant automated mutations, Encumbrance Certificates (EC), and prohibited land lists.",
        "services": [
            {"name": "Dharani Land Details Search", "code": "ROR", "desc": "Comprehensive Pattadar passbook, survey number, and Khata search."},
            {"name": "Prohibited Lands List (22-A)", "code": "PROHIBITED", "desc": "Verify if parcel is government, Wakf, forest, or court-disputed land."},
            {"name": "Encumbrance Certificate (EC)", "code": "EC", "desc": "Search registered transaction trail and mortgage liabilities."},
            {"name": "Instant Registration & Mutation", "code": "MUTATION", "desc": "Combined sale deed registration and instantaneous mutation."},
            {"name": "Cadastral Village Maps", "code": "GIS", "desc": "Digital spatial maps with survey boundary coordinates."}
        ]
    },
    {
        "id": "gujarat-anyror",
        "state": "Gujarat",
        "portal_name": "AnyRoR (Anywhere RoR Gujarat / ઈ-જમીન)",
        "english_title": "Gujarat Revenue Dept Land Records Portal",
        "hindi_title": "गुजरात एनी-आर‌ओ‌आर (VF-7/12, 8A, હક્ક પત્રક)",
        "zone": "West",
        "official_url": "https://anyror.gujarat.gov.in",
        "cadastral_gis_url": "https://iora.gujarat.gov.in",
        "mutation_url": "https://anyror.gujarat.gov.in/emutation",
        "tax_url": "https://cyberfinance.gujarat.gov.in",
        "court_url": "https://revenue.gujarat.gov.in/rcms",
        "term_anchal": "Taluka",
        "term_record": "VF-7/12 & VF-8A Extract",
        "term_plot": "Survey No (સર્વે નંબર)",
        "term_holding": "Khata Number (ખાતા નંબર)",
        "category": "State RoR Portal",
        "description": "AnyRoR Gujarat provides instant access to Village Form 7 (ownership/tenure), Village Form 12 (crops/irrigation), Village Form 8A (khatedar holding), and Village Form 6 (Hakk Patrak mutation register).",
        "services": [
            {"name": "VF-7/12 (૭/૧૨ નો ઉતારો)", "code": "ROR", "desc": "Detailed ownership, occupancy rights, and agricultural classification."},
            {"name": "VF-8A (૮-અ ખાતા ઉતારો)", "code": "8A", "desc": "Consolidated holding summary of all plots under a farmer's khata."},
            {"name": "VF-6 (હક્ક પત્રક / Ferfar Entry)", "code": "MUTATION", "desc": "Mutation trail, heir certificates, and lien/mortgage notices."},
            {"name": "135-D Notice Status", "code": "NOTICE", "desc": "Public notice compliance status prior to mutation finalization."},
            {"name": "i-ORA Online Revenue Applications", "code": "IORA", "desc": "Apply for Non-Agricultural (NA) permission and title certificates."}
        ]
    },
    {
        "id": "rajasthan-apnakhata",
        "state": "Rajasthan",
        "portal_name": "Apna Khata / E-Dharti (अपना खाता / ई-धरती)",
        "english_title": "Rajasthan Revenue Board Land Records Portal",
        "hindi_title": "राजस्थान राजस्व मण्डल अपना खाता एवं ई-धरती",
        "zone": "North",
        "official_url": "http://apnakhata.raj.nic.in",
        "cadastral_gis_url": "http://bhunaksha.raj.nic.in",
        "mutation_url": "http://apnakhata.raj.nic.in/namantaran",
        "tax_url": "https://rajkosh.rajasthan.gov.in",
        "court_url": "http://bor.rajasthan.gov.in/rcms",
        "term_anchal": "Tehsil",
        "term_record": "Jamabandi Nakal (जमाबंदी नकल)",
        "term_plot": "Khasra No (खसरा संख्या)",
        "term_holding": "Khata Number (खाता संख्या)",
        "category": "State RoR Portal",
        "description": "Apna Khata Rajasthan provides digitized Jamabandi (RoR) copies, Namantaran (mutation) application, Bhu-Naksha cadastral map verification, and Seema Gyan boundary demarcation.",
        "services": [
            {"name": "Jamabandi Nakal (जमाबंदी नकल)", "code": "ROR", "desc": "Download certified Record of Rights with tenant details and share."},
            {"name": "Namantaran Apply & Status (नामांतरण)", "code": "MUTATION", "desc": "Online mutation filing under Rajasthan Land Revenue Act."},
            {"name": "Rajasthan Bhu-Naksha GIS", "code": "GIS", "desc": "Khasra plot boundaries, canal networks, and road easements."},
            {"name": "Seema Gyan (सीमा ज्ञान)", "code": "SURVEY", "desc": "Field survey application for resolving boundary disputes."},
            {"name": "RCMS Rajasthan", "code": "COURT", "desc": "Track cases before Revenue Board Ajmer and Sub-Divisional Courts."}
        ]
    },
    {
        "id": "madhya-pradesh-mpbhulekh",
        "state": "Madhya Pradesh",
        "portal_name": "MP Bhulekh (एमपी भूलेख)",
        "english_title": "Madhya Pradesh Land Records & Bhu-Abhilekh Portal",
        "hindi_title": "मध्य प्रदेश भू-अभिलेख एवं खसरा-खतौनी पोर्टल",
        "zone": "Central",
        "official_url": "https://mpbhulekh.gov.in/mpbhulekh.do",
        "cadastral_gis_url": "https://mpbhunaksha.mp.gov.in",
        "mutation_url": "https://saara.mp.gov.in",
        "tax_url": "https://mptreasury.gov.in",
        "court_url": "https://rcms.mp.gov.in",
        "term_anchal": "Tehsil",
        "term_record": "Khasra / Khatoni RoR (खसरा / खतौनी)",
        "term_plot": "Khasra No (खसरा क्र.)",
        "term_holding": "Khata Number (खाता क्र.)",
        "category": "State RoR Portal",
        "description": "MP Bhulekh provides certified digital copies of Khasra (plot record), Khatoni (holding record), Bhu-Naksha vector maps, SAARA agricultural revenue app, and RCMS case management.",
        "services": [
            {"name": "Khasra / Khatoni View", "code": "ROR", "desc": "Search land records by District, Tehsil, Village, or Owner Name."},
            {"name": "Certified Document Copies", "code": "CERTIFIED", "desc": "Digitally signed Khasra, B-1 Khatoni, and Map copies."},
            {"name": "SAARA Revenue Suite", "code": "SAARA", "desc": "Crop girdawari, natural calamity relief, and mutation orders."},
            {"name": "MP Bhu-Naksha GIS", "code": "GIS", "desc": "Cadastral maps showing parcel subdivisions and road connectivity."},
            {"name": "RCMS MP Revenue Courts", "code": "COURT", "desc": "Check hearing dates and stay orders in Tehsildar & Collector courts."}
        ]
    },
    {
        "id": "west-bengal-banglarbhumi",
        "state": "West Bengal",
        "portal_name": "Banglarbhumi (বাংলারভূমি)",
        "english_title": "West Bengal Land & Land Reforms Portal",
        "hindi_title": "पश्चिम बंगाल बांगलारभूमि (খতিয়ান ও প্লট)",
        "zone": "East",
        "official_url": "http://banglarbhumi.gov.in",
        "cadastral_gis_url": "http://banglarbhumi.gov.in/MouzaMap",
        "mutation_url": "http://banglarbhumi.gov.in/Mutation",
        "tax_url": "https://wbifms.gov.in/GRIPS",
        "court_url": "http://banglarbhumi.gov.in/CourtCase",
        "term_anchal": "Block",
        "term_record": "Khatian & Plot Record",
        "term_plot": "Plot / Dag No (দাগ নম্বর)",
        "term_holding": "Khatian No (খতিয়ান নম্বর)",
        "category": "State RoR Portal",
        "description": "Banglarbhumi portal of West Bengal provides live Khatian (RoR) inspection, Plot Information (Dag), Mouza Map downloads, Online Mutation, Land Conversion, and Warish (heir) applications.",
        "services": [
            {"name": "Know Your Property (Khatian & Plot)", "code": "ROR", "desc": "View classification, area in acres, share, and rayat details."},
            {"name": "Online Mutation & Status", "code": "MUTATION", "desc": "Apply for mutation and track notice issuance under WBLR Act."},
            {"name": "Mouza Map Request (মৌজা ম্যাপ)", "code": "GIS", "desc": "Request certified copy of village cadastral sheet."},
            {"name": "Land Conversion Application", "code": "CONVERSION", "desc": "Apply for change of land classification under Section 4C."},
            {"name": "Warish Application (উত্তরাধিকার)", "code": "WARISH", "desc": "Record legal heirs on ancestor's tenancy khata."}
        ]
    },
    {
        "id": "haryana-jamabandi",
        "state": "Haryana",
        "portal_name": "Jamabandi Haryana (जमाबंदी हरियाणा)",
        "english_title": "Haryana Land Records & Jamabandi Portal",
        "hindi_title": "हरियाणा राजस्व विभाग जमाबंदी एवं वेब-हलरिस",
        "zone": "North",
        "official_url": "https://jamabandi.nic.in",
        "cadastral_gis_url": "https://jamabandi.nic.in/CadastralMaps",
        "mutation_url": "https://jamabandi.nic.in/MutationStatus",
        "tax_url": "https://egrashry.nic.in",
        "court_url": "https://jamabandi.nic.in/CourtCases",
        "term_anchal": "Tehsil / Sub-Tehsil",
        "term_record": "Nakal Jamabandi (जमाबंदी नकल)",
        "term_plot": "Khasra / Killa No (खसरा / किला नं)",
        "term_holding": "Khewat / Khatoni No",
        "category": "State RoR Portal",
        "description": "Jamabandi Haryana (Web-HALRIS) offers digital Nakal Jamabandi, Registered Deed inspection, Mutation orders, Cadastral village maps, Court Case status, and property collector rates.",
        "services": [
            {"name": "View Nakal Jamabandi", "code": "ROR", "desc": "Search ownership by Owner Name, Khewat, Khasra, or Date of Mutation."},
            {"name": "Check Mutation Status (इंतकाल)", "code": "MUTATION", "desc": "Real-time tracking of mutation sanctioning orders."},
            {"name": "Registered Deed Verification", "code": "DEED", "desc": "Verify registry deeds with sub-registrar token and party details."},
            {"name": "Cadastral Geo-Maps", "code": "GIS", "desc": "Killa-wise boundary maps with canal and tubewell layers."},
            {"name": "Revenue Court Litigation", "code": "COURT", "desc": "Search stay orders before Tehsildar, SDM, Collector, and Financial Commissioner."}
        ]
    },
    {
        "id": "punjab-jamabandi",
        "state": "Punjab",
        "portal_name": "Jamabandi Punjab (ਜਮ੍ਹਾਬੰਦੀ ਪੰਜਾਬ)",
        "english_title": "Punjab Land Records Society (PLRS) Portal",
        "hindi_title": "पंजाब लैंड रिकॉर्ड्स सोसायटी जमाबंदी एवं फर्द",
        "zone": "North",
        "official_url": "http://jamabandi.punjab.gov.in",
        "cadastral_gis_url": "http://plrs.org.in",
        "mutation_url": "http://jamabandi.punjab.gov.in/MutationDetails",
        "tax_url": "https://epay.punjab.gov.in",
        "court_url": "http://revenue.pun पंजाब.gov.in",
        "term_anchal": "Tehsil",
        "term_record": "Jamabandi (Fard / ਫ਼ਰਦ)",
        "term_plot": "Khasra / Killa No (ਖਸਰਾ ਨੰ.)",
        "term_holding": "Khewat / Khatauni",
        "category": "State RoR Portal",
        "description": "PLRS Jamabandi Punjab enables viewing and downloading certified Fard (RoR copies), tracking Inteqal (mutations), Roznamcha daily reports, and registered sale deeds.",
        "services": [
            {"name": "View Jamabandi / Fard (ਫ਼ਰਦ)", "code": "ROR", "desc": "Search land fard by Owner Name, Khewat, Khasra, or Khatauni."},
            {"name": "Mutation (Inteqal / ਇੰਤਕਾਲ) Status", "code": "MUTATION", "desc": "Track mutation sanction and verification progress."},
            {"name": "Roznamcha (ਰੋਜ਼ਨਾਮਚਾ)", "code": "LOG", "desc": "Patwari daily diary entries of mutations, transfers, and seizures."},
            {"name": "Registry Deed Details", "code": "DEED", "desc": "Inspect registered vasika sale deeds and execution dates."},
            {"name": "Cadastral Aks Shajra Map", "code": "GIS", "desc": "Village parcel map layouts with boundary measurements."}
        ]
    },
    {
        "id": "odisha-bhulekh",
        "state": "Odisha",
        "portal_name": "Bhulekh Odisha (ଭୂଲେଖ ଓଡ଼ିଶା)",
        "english_title": "Odisha Land Records & Bhulekh Portal",
        "hindi_title": "ओडिशा भूलेख (RoR, ଖତିଆନ, ପ୍ଲଟ)",
        "zone": "East",
        "official_url": "http://bhulekh.ori.nic.in",
        "cadastral_gis_url": "http://bhunakshaodisha.nic.in",
        "mutation_url": "http://edistrict.odisha.gov.in",
        "tax_url": "https://odishatreasury.gov.in",
        "court_url": "http://rcms.odisha.gov.in",
        "term_anchal": "Tahasil",
        "term_record": "RoR / Khatian (ଖତିଆନ)",
        "term_plot": "Plot No (ପ୍ଲଟ ନଂ)",
        "term_holding": "Khata No (ଖାତା ନଂ)",
        "category": "State RoR Portal",
        "description": "Bhulekh Odisha provides Khatiyan view, Tenant share details, Plot status, BhuNaksha Odisha spatial maps, e-Mutation status, and Tahasil-level revenue administration data.",
        "services": [
            {"name": "View RoR (Record of Rights)", "code": "ROR", "desc": "Search by Khatiyan No, Tenant Name, or Plot Number across all districts."},
            {"name": "Bhunaksha Odisha GIS", "code": "GIS", "desc": "Digital map boundaries with area computation and road access."},
            {"name": "e-Mutation Application", "code": "MUTATION", "desc": "File online mutation and track e-District case delivery."},
            {"name": "Tahasil Info & Circle Rates", "code": "INFO", "desc": "Jurisdiction boundaries and benchmark property valuation."},
            {"name": "RCMS Odisha Court Cases", "code": "COURT", "desc": "Check revenue appeals before Collector and Revenue Divisional Commissioner."}
        ]
    },
    {
        "id": "chhattisgarh-bhuiyan",
        "state": "Chhattisgarh",
        "portal_name": "Bhuiyan (भुइयां छत्तीसगढ़)",
        "english_title": "Chhattisgarh Land Records Modernization Portal",
        "hindi_title": "छत्तीसगढ़ भुइयां खसरा (बी-I / पी-II) अभिलेख",
        "zone": "Central",
        "official_url": "https://bhuiyan.cg.nic.in",
        "cadastral_gis_url": "https://bhunaksha.cg.nic.in",
        "mutation_url": "https://bhuiyan.cg.nic.in/Namantaran.aspx",
        "tax_url": "https://ekoshonline.cg.nic.in",
        "court_url": "https://revenue.cg.nic.in/rcms",
        "term_anchal": "Tehsil",
        "term_record": "B-I (Khatoni) & P-II (Khasra)",
        "term_plot": "Khasra No (खसरा क्र.)",
        "term_holding": "Khata Number (खाता संख्या)",
        "category": "State RoR Portal",
        "description": "Bhuiyan CG provides B-I (Khatoni summary), P-II (Khasra plot detail), digitally signed Nakal downloads, online Namantaran (mutation), and Bhunaksha CG integration.",
        "services": [
            {"name": "B-I Khatoni & P-II Khasra", "code": "ROR", "desc": "Certified digital copies with QR codes and digital signature verification."},
            {"name": "Online Namantaran (Mutation)", "code": "MUTATION", "desc": "Apply for ownership transfer and inspect public notice hearings."},
            {"name": "Bhunaksha CG (भू-नक्शा)", "code": "GIS", "desc": "Interactive cadastral village maps with Khasra boundaries."},
            {"name": "Crop / Girdawari Report", "code": "GIRDAWARI", "desc": "Seasonal crop registration and Rajiv Gandhi Kisan Nyay linkage."},
            {"name": "RCMS Chhattisgarh", "code": "COURT", "desc": "Case management system for Naib Tehsildar, Tehsildar & Collector courts."}
        ]
    },
    {
        "id": "kerala-entebhoomi",
        "state": "Kerala",
        "portal_name": "Ente Bhoomi / E-Rekha (എന്റെ ഭൂമി / ഇ-രേഖ)",
        "english_title": "Kerala Survey & Land Records Portal",
        "hindi_title": "केरल एन्ते भूमि एवं ई-रेखा भूमि अभिलेख",
        "zone": "South",
        "official_url": "https://entebhoomi.kerala.gov.in",
        "cadastral_gis_url": "http://erekha.kerala.gov.in",
        "mutation_url": "https://revenue.kerala.gov.in",
        "tax_url": "https://etreasury.kerala.gov.in",
        "court_url": "https://revenue.kerala.gov.in/disputes",
        "term_anchal": "Taluk",
        "term_record": "Thandaper & Resurvey Record",
        "term_plot": "Survey / Resurvey / Block No",
        "term_holding": "Thandaper Account No (തണ്ടപ്പേര്)",
        "category": "State RoR Portal",
        "description": "Ente Bhoomi and E-Rekha offer digital Resurvey records, Old Survey records, Field Measurement Book (FMB) sketches, Pokkuvaravu (mutation), and Unique Thandaper Account (UTA).",
        "services": [
            {"name": "E-Rekha Survey Record Search", "code": "ROR", "desc": "Download Old Survey and Re-survey Settlement records."},
            {"name": "FMB Sketch (Field Measurement Book)", "code": "GIS", "desc": "Download certified village survey field measurement books."},
            {"name": "Unique Thandaper (UTA / തണ്ടപ്പേര്)", "code": "UTA", "desc": "Aadhaar-linked single identity for all land holdings in Kerala."},
            {"name": "Pokkuvaravu (പോക്കുവരവ് / Mutation)", "code": "MUTATION", "desc": "Online mutation and ownership transfer tracking."},
            {"name": "Village & Block Cadastral Maps", "code": "MAP", "desc": "Geo-referenced spatial boundaries and topographical features."}
        ]
    },
    {
        "id": "tamil-nadu-pattachitta",
        "state": "Tamil Nadu",
        "portal_name": "Anytime / e-Services Patta Chitta (பட்டா / சிட்டா)",
        "english_title": "Tamil Nadu Land Records & e-Services Portal",
        "hindi_title": "तमिलनाडु पट्टा-चिट्टा एवं एफएमबी भूलेख पोर्टल",
        "zone": "South",
        "official_url": "https://eservices.tn.gov.in/eservicesnew/index.html",
        "cadastral_gis_url": "https://eservices.tn.gov.in/eservicesnew/land/fmb.html",
        "mutation_url": "https://tamilnilam.tn.gov.in",
        "tax_url": "https://karuvoolam.tn.gov.in",
        "court_url": "https://revenue.tn.gov.in",
        "term_anchal": "Taluk",
        "term_record": "Patta / Chitta (பட்டா / சிட்டா)",
        "term_plot": "Survey / Sub-division No",
        "term_holding": "Patta Number (பட்டா எண்)",
        "category": "State RoR Portal",
        "description": "Tamil Nadu's e-Services portal allows instant viewing of Patta / Chitta extracts, FMB sketches, TSLR (Town Survey Land Register) extracts, Patta verification, and Tamil Nilam online mutation.",
        "services": [
            {"name": "View Patta / Chitta (பட்டா / சிட்டா)", "code": "ROR", "desc": "View owner name, total area in hectares/ares, and land classification."},
            {"name": "Verify Patta / Chitta Certificate", "code": "VERIFY", "desc": "Verify QR-coded digital copy validity against government database."},
            {"name": "View FMB Sketch (புலப்பட வரைபடம்)", "code": "GIS", "desc": "Detailed field measurement boundary diagram with dimensions."},
            {"name": "TSLR Extract (Urban Land Register)", "code": "TSLR", "desc": "Town survey register for municipal corporations and towns."},
            {"name": "Tamil Nilam Online Patta Transfer", "code": "MUTATION", "desc": "Apply for full field or sub-division Patta transfer online."}
        ]
    },
    {
        "id": "himachal-pradesh-himbhoomi",
        "state": "Himachal Pradesh",
        "portal_name": "Himbhoomi (हिमभूमि)",
        "english_title": "HP Land Records & Jamabandi Portal",
        "hindi_title": "हिमाचल प्रदेश हिमभूमि जमाबंदी एवं शजरा अक्स",
        "zone": "North",
        "official_url": "http://admis.hp.nic.in/himbhoomi",
        "cadastral_gis_url": "https://lrc.hp.nic.in/bhunaksha",
        "mutation_url": "http://admis.hp.nic.in/himbhoomi",
        "tax_url": "https://himkosh.hp.nic.in",
        "court_url": "https://revenue.hp.gov.in",
        "term_anchal": "Tehsil / Sub-Tehsil",
        "term_record": "Jamabandi Nakal (जमाबंदी नकल)",
        "term_plot": "Khasra No (खसरा संख्या)",
        "term_holding": "Khewat / Khatauni",
        "category": "State RoR Portal",
        "description": "Himbhoomi provides online Jamabandi copies, Shajra Aks cadastral maps, Mutation (Inteqal) status, Section 118 permission tracking (land purchase by non-agriculturists), and Circle Rates.",
        "services": [
            {"name": "View Jamabandi Nakal", "code": "ROR", "desc": "Search by Khewat, Khatoni, Khasra, or Owner Name across all tehsils."},
            {"name": "Shajra Aks (Cadastral Map)", "code": "GIS", "desc": "Spatial layout of mountain plots with contours and road rights-of-way."},
            {"name": "Mutation (Inteqal) Status", "code": "MUTATION", "desc": "Track mutation sanction by Revenue Officers."},
            {"name": "Section 118 Permission Tracker", "code": "SEC118", "desc": "Verify statutory government permissions for land acquisition in HP."},
            {"name": "HP Revenue Court Management", "code": "COURT", "desc": "Check revenue appeal proceedings in Financial Commissioner's court."}
        ]
    },
    {
        "id": "uttarakhand-devbhoomi",
        "state": "Uttarakhand",
        "portal_name": "Devbhoomi / Bhulekh UK (देवभूमि भूलेख)",
        "english_title": "Uttarakhand Board of Revenue Land Records Portal",
        "hindi_title": "उत्तराखंड देवभूमि भूलेख एवं खतौनी नकल",
        "zone": "North",
        "official_url": "http://bhulekh.uk.gov.in",
        "cadastral_gis_url": "http://bhunaksha.uk.gov.in",
        "mutation_url": "http://bhulekh.uk.gov.in/eMutation",
        "tax_url": "https://ekosh.uk.gov.in",
        "court_url": "http://rcms.uk.gov.in",
        "term_anchal": "Tehsil",
        "term_record": "Khatauni RoR (खतौनी नकल)",
        "term_plot": "Khasra No (खसरा संख्या)",
        "term_holding": "Khata Number (खाता संख्या)",
        "category": "State RoR Portal",
        "description": "Devbhoomi Bhulekh UK provides RoR Khatauni copies, 1:1 Khasra transfer logs, online Dakhil-Kharij status, Bhu-Naksha spatial maps, and circle rate calculator.",
        "services": [
            {"name": "Khatauni RoR Copy (खतौनी उद्धरण)", "code": "ROR", "desc": "Certified copy showing tenure holders, plot share, and fasli year."},
            {"name": "Plot Transfer Log & History", "code": "HISTORY", "desc": "Historical alienation and sale transfer timeline for each Khasra."},
            {"name": "Uttarakhand BhuNaksha GIS", "code": "GIS", "desc": "Vectorized hilly cadastral terrain maps with boundaries."},
            {"name": "e-Mutation (दाखिल-खारिज स्थिति)", "code": "MUTATION", "desc": "Track mutation orders in Tehsildar & Naib Tehsildar courts."},
            {"name": "RCMS Uttarakhand Courts", "code": "COURT", "desc": "Revenue court litigation search across 13 districts."}
        ]
    },
    {
        "id": "assam-dharitree",
        "state": "Assam",
        "portal_name": "Dharitree / ILRMS (ধৰিত্ৰী / ILRMS)",
        "english_title": "Assam Integrated Land Records Management System",
        "hindi_title": "असम धरीत्री एवं मिशन बसुंधरा भूलेख पोर्टल",
        "zone": "North-East",
        "official_url": "https://revenueassam.nic.in",
        "cadastral_gis_url": "https://landrecords.assam.gov.in",
        "mutation_url": "https://basundhara.assam.gov.in",
        "tax_url": "https://egrasassam.gov.in",
        "court_url": "https://revenueassam.nic.in/rcms",
        "term_anchal": "Revenue Circle",
        "term_record": "Jamabandi (Chitha / জমাবন্দী)",
        "term_plot": "Dag No (দাগ নম্বৰ)",
        "term_holding": "Patta No (পাট্টা নম্বৰ)",
        "category": "State RoR Portal",
        "description": "Assam Dharitree and Mission Basundhara offer Jamabandi (Chitha) copies, online mutation by right of inheritance and deed, Patta transfer, land conversion, and e-Panjeeyan integration.",
        "services": [
            {"name": "View Jamabandi / Chitha (জমাবন্দী)", "code": "ROR", "desc": "Search by District, Circle, Village, Patta No, or Dag No."},
            {"name": "Mission Basundhara Services", "code": "BASUNDHARA", "desc": "Allottee settlement, land conversion, and instant mutation services."},
            {"name": "Online Mutation (নামজাৰী)", "code": "MUTATION", "desc": "Apply for mutation by sale deed or succession."},
            {"name": "Cadastral Village Maps", "code": "GIS", "desc": "Digital revenue map sheets with Dag boundaries."},
            {"name": "Land Revenue (Khazana) Payment", "code": "TAX", "desc": "Pay annual land revenue khazana online with instant e-Receipt."}
        ]
    },
    {
        "id": "tripura-jamitripura",
        "state": "Tripura",
        "portal_name": "Jami Tripura (জমি ত্রিপুরা)",
        "english_title": "Tripura Land Records & e-Jami Portal",
        "hindi_title": "त्रिपुरा ई-जामी भू-अभिलेख पोर्टल",
        "zone": "North-East",
        "official_url": "https://jami.tripura.gov.in",
        "cadastral_gis_url": "https://jami.tripura.gov.in/map",
        "mutation_url": "https://jami.tripura.gov.in/mutation",
        "tax_url": "https://tripuratreasury.gov.in",
        "court_url": "https://jami.tripura.gov.in/rcms",
        "term_anchal": "Revenue Circle / Sub-Division",
        "term_record": "e-Jami Khatian RoR",
        "term_plot": "Plot / Dag No",
        "term_holding": "Khatian No",
        "category": "State RoR Portal",
        "description": "Jami Tripura provides online Khatian (Record of Rights), digitized plot maps, online mutation status, encumbrance certificates, and revenue litigation logs.",
        "services": [
            {"name": "View e-Jami Khatian (খতিয়ান)", "code": "ROR", "desc": "Search by District, Sub-Division, Revenue Circle, Mouza, and Khatian."},
            {"name": "Online Mutation Status", "code": "MUTATION", "desc": "Real-time mutation process tracking and field verification status."},
            {"name": "Cadastral Plot Map (প্লট ম্যাপ)", "code": "GIS", "desc": "Vector cadastral sheets with plot numbers and landmarks."},
            {"name": "Land Valuation & Stamp Duty", "code": "TAX", "desc": "Circle rate valuation for property registrations in Tripura."}
        ]
    },
    {
        "id": "manipur-louchapathap",
        "state": "Manipur",
        "portal_name": "Louchapathap (লৌচাপাথাপ)",
        "english_title": "Manipur Land Records & Jamabandi Portal",
        "hindi_title": "मणिपुर लौचापाथाप जमाबंदी एवं पट्टा पोर्टल",
        "zone": "North-East",
        "official_url": "https://louchapathap.nic.in",
        "cadastral_gis_url": "https://louchapathap.nic.in/map",
        "mutation_url": "https://louchapathap.nic.in/mutation",
        "tax_url": "https://manipurtresury.gov.in",
        "court_url": "https://louchapathap.nic.in/court",
        "term_anchal": "Sub-Division / SDO",
        "term_record": "Jamabandi / Patta (জামাবন্দী)",
        "term_plot": "Dag No (দাগ নং)",
        "term_holding": "Patta No (পাট্টা নং)",
        "category": "State RoR Portal",
        "description": "Louchapathap Manipur offers Jamabandi / Patta inspection, Dag number details, mutation tracking, revenue rates, and cadastral maps across the valley and hill districts.",
        "services": [
            {"name": "View Jamabandi / Patta", "code": "ROR", "desc": "Search land records by District, SDO Circle, Village, and Patta number."},
            {"name": "Dag Information System", "code": "DAG", "desc": "Inspect land area, revenue class, and pattadar shares."},
            {"name": "Online Mutation Status", "code": "MUTATION", "desc": "Track application status for change of ownership."},
            {"name": "Revenue Map Boundary Views", "code": "GIS", "desc": "Village cadastral maps with survey boundaries."}
        ]
    },
    {
        "id": "goa-dslr",
        "state": "Goa",
        "portal_name": "Goa Land Records DSLR (संचालनालय भूमी अभिलेख)",
        "english_title": "Goa Directorate of Settlement & Land Records",
        "hindi_title": "गोवा भूमी अभिलेख (Form I & XIV, Form D)",
        "zone": "West",
        "official_url": "https://egov.goa.nic.in/dslr/f114new.aspx",
        "cadastral_gis_url": "https://dslr.goa.gov.in",
        "mutation_url": "https://dslr.goa.gov.in/mutation",
        "tax_url": "https://egov.goa.nic.in/echallan",
        "court_url": "https://dslr.goa.gov.in/courtcases",
        "term_anchal": "Taluka",
        "term_record": "Form I & XIV RoR",
        "term_plot": "Survey / Sub-Division No",
        "term_holding": "Survey Property No",
        "category": "State RoR Portal",
        "description": "Goa DSLR provides digital Form I & XIV (RoR), Form D (Mutation entry), Title confirmation certificates, certified Cadastral plans, and partition case tracking.",
        "services": [
            {"name": "View Form I & XIV", "code": "ROR", "desc": "Inspect occupants, tenant rights, other rights, and area in sq. meters."},
            {"name": "Form D (Mutation Notice)", "code": "MUTATION", "desc": "Track mutation entries and statutory 30-day objection periods."},
            {"name": "Certified Cadastral Plans", "code": "GIS", "desc": "Download certified survey plans showing plot dimensions."},
            {"name": "Title Confirmation & Partition", "code": "TITLE", "desc": "Verify ancestral title deeds and Comunidade land status."}
        ]
    },
    {
        "id": "delhi-dlrc",
        "state": "Delhi (NCT)",
        "portal_name": "Delhi Land Records / DLRC (दिल्ली भूलेख)",
        "english_title": "Delhi Revenue Department Land Records Portal",
        "hindi_title": "दिल्ली राजस्व विभाग भूलेख एवं खतौनी",
        "zone": "Union Territory",
        "official_url": "https://dlrc.delhi.gov.in",
        "cadastral_gis_url": "https://revenue.delhi.gov.in/gis",
        "mutation_url": "https://edistrict.delhigovt.nic.in",
        "tax_url": "https://delhi.gov.in/revenue",
        "court_url": "https://revenue.delhi.gov.in/courtcases",
        "term_anchal": "Tehsil / Sub-Division",
        "term_record": "Khatauni RoR & Khasra Girdawari",
        "term_plot": "Khasra No (खसरा नं)",
        "term_holding": "Khata Number",
        "category": "State RoR Portal",
        "description": "Delhi DLRC provides digitized Khatauni RoR, Khasra Girdawari records, Aks Shajra maps, e-District Delhi mutation workflow, and Tehsildar revenue court status.",
        "services": [
            {"name": "View ROR Khatauni (खतौनी नकल)", "code": "ROR", "desc": "Search by District, Sub-Division, Village, Khata No, or Khasra No."},
            {"name": "Khasra Girdawari Records", "code": "GIRDAWARI", "desc": "Inspect seasonal cultivation and possession status in rural villages."},
            {"name": "Aks Shajra Cadastral Maps", "code": "GIS", "desc": "High-resolution village layout plans and Lal Dora boundaries."},
            {"name": "e-District Online Mutation", "code": "MUTATION", "desc": "Apply for land mutation and track Tehsildar verification."}
        ]
    },
    {
        "id": "central-dilrmp-bhuaadhaar",
        "state": "National / Central",
        "portal_name": "Department of Land Resources (DILRMP / Bhu-Aadhaar)",
        "english_title": "National Oversight & Bhu-Aadhaar (ULPIN) Central Hub",
        "hindi_title": "भूमि संसाधन विभाग (भू-आधार / DILRMP राष्ट्रीय पोर्टल)",
        "zone": "Central & Allied",
        "official_url": "https://dolr.gov.in/en/programmes-schemes/dilrmp-2/",
        "cadastral_gis_url": "https://bhu-aadhaar.dilrmp.gov.in",
        "mutation_url": "https://dolr.gov.in",
        "tax_url": "https://dolr.gov.in",
        "court_url": "https://dolr.gov.in",
        "term_anchal": "State / District / Sub-Division",
        "term_record": "14-Digit Bhu-Aadhaar (ULPIN)",
        "term_plot": "Geo-Centroid Spatial Coordinate",
        "term_holding": "Unique Land Parcel ID",
        "category": "Central & Allied Tracking",
        "description": "The national apex standard for Digital India Land Records Modernization Programme (DILRMP). Mandates the 14-digit Unique Land Parcel Identification Number (ULPIN / Bhu-Aadhaar) based on international geo-spatial standards.",
        "services": [
            {"name": "14-Digit Bhu-Aadhaar Generator & Lookup", "code": "ULPIN", "desc": "Generate and verify canonical geo-coded 14-digit land identity."},
            {"name": "National Cadastral Standardization", "code": "GIS", "desc": "Harmonized WMS/WFS spatial layers across all 28 states & 8 UTs."},
            {"name": "Inter-Departmental Data Exchange", "code": "INTEROP", "desc": "Unified API bridge linking Revenue, Registry, Banks, and Courts."},
            {"name": "National DILRMP Progress Dashboard", "code": "DASHBOARD", "desc": "Real-time state modernization index, computerization, and survey progress."}
        ]
    },
    {
        "id": "central-ecourts-litigation",
        "state": "National / Central",
        "portal_name": "e-Courts Services (राष्ट्रीय ई-कोर्ट्स सेवाएँ)",
        "english_title": "National Judicial Data Grid & Revenue Litigation Checker",
        "hindi_title": "ई-कोर्ट्स सेवाएँ — भूमि एवं राजस्व वाद सत्यापन",
        "zone": "Central & Allied",
        "official_url": "https://ecourts.gov.in",
        "cadastral_gis_url": "https://njdg.ecourts.gov.in",
        "mutation_url": "https://ecourts.gov.in",
        "tax_url": "https://ecourts.gov.in",
        "court_url": "https://ecourts.gov.in/ecourts_home",
        "term_anchal": "District & Sessions Court / High Court",
        "term_record": "CNR Number (16-Digit)",
        "term_plot": "Suit Property / Khasra No",
        "term_holding": "Case Number",
        "category": "Central & Allied Tracking",
        "description": "Official nationwide e-Courts platform and National Judicial Data Grid (NJDG). Enables automated verification of title suits, partition disputes, stay orders, injunctions, and Lis Pendens (Sec 52 TPA) risks across all Indian courts.",
        "services": [
            {"name": "16-Character CNR Case Search", "code": "CNR", "desc": "Search court cases by universal Case Number Record across India."},
            {"name": "Civil Title & Partition Suit Scanner", "code": "TITLE_SUIT", "desc": "Detect pending title challenges, boundary disputes, and injunctions."},
            {"name": "Lis Pendens (Sec 52 TPA) Risk Analyzer", "code": "LIS_PENDENS", "desc": "Evaluates statutory alienation restrictions on properties under active litigation."},
            {"name": "Interim Stay Order & Injunction Alerts", "code": "STAY_ORDER", "desc": "Immediate flags for status-quo orders restraining sale or mutation."}
        ]
    }
]

def get_all_registered_portals() -> List[Dict[str, Any]]:
    return ALL_PORTALS_REGISTRY

def get_portal_by_state(state_name: str) -> Dict[str, Any]:
    norm = state_name.strip().lower()
    for p in ALL_PORTALS_REGISTRY:
        if p["state"].lower() == norm or norm in p["id"].lower() or norm in p["portal_name"].lower():
            return p
    # Fallback to general DILRMP portal
    return ALL_PORTALS_REGISTRY[-2]
